### PR TITLE
Fixed out of memory when uploading big file

### LINKED ISSUE #259: [Bug]: OutOfMemoryError when uploading big file
### What happened?

When I upload big ZIP file with music I get `java.lang.OutOfMemoryError: Java heap space`.

### Steps to reproduce

1. Set memory limit below 500MB.
2. Login into Airsonic, go to `More`.
3. Try to upload ZIP file near 500MB.
4. Get [stacktrace](https://github.com/kagemomiji/airsonic-advanced/files/12267142/big-upload-stacktrace.txt).

### Version

11.1.2 (Stable)

### Version Detail

and from master

### Operating System

Windows and Linux

### Java Version

17

### Database

Other

### DB Detail

Postgres 15 and HSQLDB

### Configuration paramter

To reproduce with files more than 500 MB, change upload limits:
```
spring.servlet.multipart.max-file-size=3GB
spring.servlet.multipart.max-request-size=3GB
```

### Proxy Server

_No response_

### client detail

_No response_

### language

None

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by zc-devs**
Closes #259.

Tests with 2GB Zip file.
```
spring.servlet.multipart.max-file-size=3GB
spring.servlet.multipart.max-request-size=3GB
```

Before patch:
Screenshot 2023-08-05 155414
Screenshot 2023-08-05 155640

After patch:
Screenshot 2023-08-05 155733
Screenshot 2023-08-05 155849

### CODE REVIEW

**Comment by zc-devs** [comment]
https://stackoverflow.com/questions/49304767/the-request-was-rejected-because-its-size-spring-tomcat
https://spring.io/guides/gs/uploading-files/
https://stackoverflow.com/questions/51893585/java-lang-outofmemoryerror-java-heap-space-while-uploading-1-gb-file-in-spri

File: airsonic-main/src/main/java/org/airsonic/player/upload/MonitoredMultipartFile.java [hunk 1]
```diff
@@ -67,10 +68,9 @@ public InputStream getInputStream() throws IOException {
...
     public void transferTo(File dest) throws IOException, IllegalStateException {
-        try (
-            FileOutputStream fos = new FileOutputStream(dest);
-            MonitoredOutputStream monitoredOutputStream = new MonitoredOutputStream(fos, listener)) {
-            monitoredOutputStream.write(file.getBytes());
-        }
+        InputStream inputStream = file.getInputStream();
+        FileOutputStream outputStream = new FileOutputStream(dest);
+        MonitoredOutputStream monitoredOutputStream = new MonitoredOutputStream(outputStream, listener);
+        FileCopyUtils.copy(inputStream, monitoredOutputStream);
```
Comment (kagemomiji) [inline airsonic-main/src/main/java/org/airsonic/player/upload/MonitoredMultipartFile.java:74]: @zc-devs 
Thank you for your contribution!
I noticed you're removing the try-with-resource statement for the OutputStream. This ensures that the stream is automatically closed, so there's no need for an explicit close() call. Please make sure not to remove the try-with-resource usage, as it's a more efficient and safer way to handle resource management.

```suggestion
        InputStream inputStream = file.getInputStream();
        try (
            FileOutputStream outputStream = new FileOutputStream(dest);
            MonitoredOutputStream monitoredOutputStream = new MonitoredOutputStream(outputStream, listener)) {
                FileCopyUtils.copy(inputStream, monitoredOutputStream);
         }
```

Comment (zc-devs) [reply airsonic-main/src/main/java/org/airsonic/player/upload/MonitoredMultipartFile.java:74]: org.springframework.util.FileCopyUtils#copy(java.io.InputStream, java.io.OutputStream) already closes both streams.

> Copy the contents of the given InputStream to the given OutputStream. Closes both streams when done.

**Review by kagemomiji — APPROVED** [review]
LGTM
